public class DocParserBarcodeData {

        public String id;
        public String document_id;
        public String remote_id;
        public String file_name;
        public String media_link;
        public String media_link_original;
        public String media_link_data;
        public Integer page_count;
        public String uploaded_at;
        public String processed_at;
        public List<BarcodeDetails> barcodedata;
        public BarcodeDetails ccadata;
        public BarcodeDetails wafdata;
        public List<BarcodeDetails> wafdetails;
        public List<BarcodeDetails> ccadetails;
    }